language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- python -m padvinder.test
notifications:
  slack:
    secure: Uj24bLmXO4U+q0bLeJoTwR1nm8ENBWdlj6F0NY1BMbkFak+s2DzDtQxhitziyre1qEyPvLfOH7UepS1csjk1BZw48pGXWAA7sEUFdWE90qXRBl7DlLrdoeWP4IAQxHHHBt9fLBDjGdwLX3GLqJDblbReTF/Ep2dI6OlRJiSYWK6TKnVMZRSQvahr/AoFgMfZIrnfE/fxIrJYR4P+QoSHP6LHGeC6jqZq7drcN9dzla61T+vkTVzHLrAh6OYJbAalU0JUv+a7DyMMoNXTSOSz+5OWC1MLgj/xwYM3ZklnqAqBDrjqAtF0mTUV0Yw1IcfcrozXJQjZ4CuWFxUxq4ZlIQonmN667ygGSzPcUrNuUSOmAwqEFsoMF8DiffHhhgC1xey0NXHv79dEIVNtnxbAc6KkodJ0j2gbGVhNH4evhjBXMuiyvfvQq4v+2mj5yWWYNum6hm8hp/7wR6pGKvPElu3d7DybDd9R36ejMPvYijlcCml8MSCVuV6VFCudiGFsnwYOiHirfQJD8zhFZzD9BzUvx0egWyWEoGNJ9fo1BGklMDVKPji5pJlPvOVJyimhQvHtVsyFTq0+812Qbp90vyz8BhTXwZbAY0VWqEzzEGbCvfh6LPofMduHIbZ7gS+El/fIPhKH31qSV3YuFhY4MoBfvT45kznYreSAe79A5YQ=
